# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-20 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=40)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excercise', models.CharField(max_length=150)),
                ('repeat', models.IntegerField()),
                ('reiteration', models.IntegerField()),
                ('date_train', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=19)),
                ('first_name', models.CharField(max_length=19)),
                ('last_name', models.CharField(max_length=19)),
            ],
        ),
    ]
